# Generated by Django 5.2 on 2025-05-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('admin', 'Админ'), ('manager', 'Менеджер'), ('moderator', 'Модератор')], default='user', max_length=10),
        ),
    ]
