# Generated by Django 5.2 on 2025-05-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Telegram ID'),
        ),
    ]
