# Стадия сборки
FROM node:18 AS builder
WORKDIR /app
COPY package*.json ./
ENV NODE_OPTIONS="--max-old-space-size=2048"
RUN npm install
COPY . .
RUN npm run build

# Финальный образ
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80