# Стадия сборки
FROM node:18 AS builder
WORKDIR /app

# Копируем только package.json сначала для кэширования зависимостей
COPY package*.json ./
COPY .env.production ./

# Установка зависимостей с очисткой кэша
RUN npm install --legacy-peer-deps && npm cache clean --force

# Копируем остальные файлы
COPY . .

# Сборка проекта
ENV NODE_OPTIONS="--max-old-space-size=2048"
RUN npm run build