version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: realty_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    environment:
      - APP_ENV=development
      - DJANGO_SETTINGS_MODULE=config.settings
      - POSTGRES_DB=realty_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DB_HOST=db
      - DEBUG=true
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api
    command: npm run dev

  telegrambot:
    build: ./telegrambot
    volumes:
      - ./telegrambot:/app
    environment:
      - APP_ENV=development
      - BOT_TOKEN=${BOT_TOKEN_DEV}
      - WEBHOOK_TOKEN=${WEBHOOK_TOKEN_DEV}
      - API_URL=http://backend:8000
      - API_TOKEN=${API_TOKEN_DEV}
    ports:
      - "8081:8081"
    depends_on:
      - backend

volumes:
  postgres_data: