# Generated by Django 5.2 on 2025-05-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('visits', models.IntegerField(default=0)),
                ('new_visits', models.IntegerField(default=0)),
                ('new_registers', models.IntegerField(default=0)),
                ('new_applications', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Дневная статистика',
                'verbose_name_plural': 'Дневная статистика',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DailyIPLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'IP лог посещения',
                'verbose_name_plural': 'IP логи посещений',
                'unique_together': {('ip_address', 'date')},
            },
        ),
    ]
