# Generated by Django 5.2 on 2025-06-03 16:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(50)], verbose_name='Имя'),
        ),
    ]
