# Generated by Django 5.2 on 2025-05-29 00:55

import apartment.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(choices=[('apartment', 'Квартира'), ('apartments', 'Апартаменты'), ('studio', 'Студия')], default='apartment', max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('total_area', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Общая площадь (м²)')),
                ('living_area', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Жилая площадь (м²)')),
                ('kitchen_area', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Площадь кухни (м²)')),
                ('floor', models.PositiveIntegerField(verbose_name='Этаж')),
                ('total_floors', models.PositiveIntegerField(verbose_name='Этажность дома')),
                ('rooms', models.PositiveIntegerField(verbose_name='Количество комнат')),
                ('bathroom_type', models.CharField(choices=[('separate', 'Раздельный'), ('combined', 'Совмещенный')], default='combined', max_length=20, verbose_name='Санузел')),
                ('renovation', models.CharField(choices=[('rough', 'Черновая'), ('clean', 'Чистовая'), ('euro', 'Евроремонт'), ('design', 'Дизайнерский')], default='clean', max_length=20, verbose_name='Ремонт')),
                ('balcony', models.PositiveIntegerField(default=0, verbose_name='Количество балконов/лоджий')),
                ('view', models.CharField(choices=[('yard', 'Двор'), ('street', 'Улица'), ('park', 'Парк')], default='yard', max_length=20, verbose_name='Вид из окна')),
                ('construction_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год постройки')),
                ('last_renovation_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год ремонта')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('deal_type', models.CharField(choices=[('sale', 'Продажа'), ('rent', 'Аренда')], default='sale', max_length=20, verbose_name='Тип сделки')),
                ('deposit', models.PositiveIntegerField(blank=True, null=True, verbose_name='Залог (для аренды)')),
                ('utilities', models.CharField(blank=True, max_length=100, null=True, verbose_name='Коммунальные платежи')),
                ('bargain', models.BooleanField(default=False, verbose_name='Возможен торг')),
                ('title', models.CharField(max_length=55, verbose_name='Заголовок объявления')),
                ('description', models.TextField(verbose_name='Описание')),
                ('features', models.TextField(blank=True, null=True, verbose_name='Особенности')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Квартира',
                'verbose_name_plural': 'Квартиры',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApartmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apartment.models.apartment_image_upload_path)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='apartment.apartment')),
            ],
        ),
    ]
