# Generated by Django 5.2 on 2025-04-20 21:01

import apartment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apartment.models.apartment_image_upload_path),
        ),
    ]
