# Generated by Django 5.2 on 2025-08-19 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0002_remove_unused_fields_add_range_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='floor_from',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='floor_to',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='kitchen_area_from',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='kitchen_area_to',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='living_area_from',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='living_area_to',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='rooms_from',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='rooms_to',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='total_area_from',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='total_area_to',
        ),
        migrations.AddField(
            model_name='apartment',
            name='floor',
            field=models.PositiveIntegerField(blank=True, help_text='Для домов можно оставить пустым', null=True, verbose_name='Этаж'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='kitchen_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Площадь кухни (м²)'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='living_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Жилая площадь (м²)'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='rooms',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Количество комнат'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='total_area',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Общая площадь (м²)'),
        ),
    ]
