# Generated by Django 5.2 on 2025-05-30 06:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0002_alter_apartment_deposit_alter_apartment_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='description',
            field=models.TextField(help_text='Рекомендуемая длина до 500 символов', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='features',
            field=models.TextField(blank=True, help_text='Ключевые особенности через запятую (до 500 символов)', null=True, verbose_name='Особенности'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='kitchen_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Площадь кухни (м²)'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='living_area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Жилая площадь (м²)'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='total_area',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Общая площадь (м²)'),
        ),
    ]
