# Generated by Django 5.2 on 2025-05-30 21:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0003_alter_apartment_description_alter_apartment_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина отклонения'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='status',
            field=models.CharField(choices=[('pending', 'На рассмотрении'), ('rejected', 'Отклонено'), ('approved', 'Принято')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='rooms',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Количество комнат'),
        ),
    ]
